name: "PestPHP (Run Pest Tests)"
description: "Run your Pest tests in your Github Actions."
author: "Sam Newby"

runs:
  using: "docker"
  image: "Dockerfile"

branding:
  icon: "check-square"
  color: "purple"
